### ISSUE TITLE
ws-butler does not work with Emacs daemon

### ISSUE THREAD

**Issue by tuhdo** [lewang/ws-butler#12]
When ws-butler is activated, it hangs the emacs daemon, prevent it from proceeding further. I used the following config:

```lisp
(require 'ws-butler)
(add-hook 'prog-mode-hook 'ws-butler-mode)
```

**Comment by anirothan** [comment]
A hook of 'after-make-frame-functions requires an argument (the frame just rendered). This why the activate-ws-butler function above causes an error when starting emacsclient.

However, even if this syntax error is corrected, the suggested solution will not work in all cases because any prog-mode buffers created before the frame is created, .e.g. you are using desktop-save-mode and it reloads them at startup, will not get ws-butler. Only those prog-mode buffers created after the frame is created will do so. Refer to https://github.com/lewang/ws-butler/issues/14 for more details and a suggested workaround.

**Comment by lewang** [comment]
Refer to #14 for details.  https://github.com/lewang/ws-butler/tree/remove-highlight-changes-mode/ is the fix branch being tested.
